import{a as p,i as f}from"./assets/vendor-96017409.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();p.defaults.headers.common["x-api-key"]="live_Mc16ejr6cQ3s1rv3AuM7sBDYNFrVKan3cwDMZWOgdClmP5Yav4a8NKNmRoTw41rh";async function m(){return(await p.get("https://api.thecatapi.com/v1/breeds")).data}async function u(e){return(await p.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`)).data}const a=document.querySelector("body"),s=document.querySelector(".select"),l=document.querySelector(".loader"),d=document.querySelector(".cat-info");s.style.display="none";document.addEventListener("DOMContentLoaded",g);s.addEventListener("change",y);async function y(){const e=s.children.selectElement,n=e.options[e.selectedIndex].value;try{d.style.display="none",l.style.display="block";const r=await u(n);l.style.display="none",v(r)}catch(r){a.innerHTML="Oops! Something went wrong! Try reloading the page!",a.style.color="#ff0000",f.error({message:"Error fetching cat information! Try again!",position:"topRight",color:"#ff0000"}),console.log(`${r.message}`)}}async function g(){try{const e=await m();l.style.display="none",h(e),s.style.display="flex"}catch(e){a.innerHTML="Oops! Something went wrong! Try reloading the page!",a.style.color="#ff0000",f.error({message:"Error fetching cat information! Try again!",position:"topRight",color:"#ff0000"}),console.log(`${e.message}`)}}function h(e){const n=e.map(({id:r,name:c})=>`<option value="${r}">${c}</option>`).join("");s.innerHTML=`<select class="breed-select" id="selectElement">${n}</select>`}function v(e){d.style.display="flex";const n=`<img class="cat-img" src="${e[0].url}" alt="${e[0].breeds[0].name}"  />
    <div class="breed-info">
      <h1 class="cat-name">${e[0].breeds[0].name}</h1>
      <p class="description">${e[0].breeds[0].description}</p>
      <h2 class="temperament">Temperament:</h2>
      <p class="temp-descr">${e[0].breeds[0].temperament}</p>
    </div>
    `;return d.innerHTML=n}
//# sourceMappingURL=commonHelpers.js.map
